// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cpp_pbtest.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_cpp_5fpbtest_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_cpp_5fpbtest_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_cpp_5fpbtest_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_cpp_5fpbtest_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_cpp_5fpbtest_2eproto;
namespace lab {
class NetPacket;
class NetPacketDefaultTypeInternal;
extern NetPacketDefaultTypeInternal _NetPacket_default_instance_;
}  // namespace lab
PROTOBUF_NAMESPACE_OPEN
template<> ::lab::NetPacket* Arena::CreateMaybeMessage<::lab::NetPacket>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace lab {

// ===================================================================

class NetPacket :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:lab.NetPacket) */ {
 public:
  NetPacket();
  virtual ~NetPacket();

  NetPacket(const NetPacket& from);
  NetPacket(NetPacket&& from) noexcept
    : NetPacket() {
    *this = ::std::move(from);
  }

  inline NetPacket& operator=(const NetPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline NetPacket& operator=(NetPacket&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const NetPacket& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NetPacket* internal_default_instance() {
    return reinterpret_cast<const NetPacket*>(
               &_NetPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(NetPacket& a, NetPacket& b) {
    a.Swap(&b);
  }
  inline void Swap(NetPacket* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline NetPacket* New() const final {
    return CreateMaybeMessage<NetPacket>(nullptr);
  }

  NetPacket* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<NetPacket>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const NetPacket& from);
  void MergeFrom(const NetPacket& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NetPacket* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "lab.NetPacket";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_cpp_5fpbtest_2eproto);
    return ::descriptor_table_cpp_5fpbtest_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPayloadFieldNumber = 5,
    kSeqFieldNumber = 1,
    kAckFieldNumber = 2,
    kTimestampFieldNumber = 4,
    kAckBitsFieldNumber = 3,
  };
  // bytes payload = 5;
  void clear_payload();
  const std::string& payload() const;
  void set_payload(const std::string& value);
  void set_payload(std::string&& value);
  void set_payload(const char* value);
  void set_payload(const void* value, size_t size);
  std::string* mutable_payload();
  std::string* release_payload();
  void set_allocated_payload(std::string* payload);
  private:
  const std::string& _internal_payload() const;
  void _internal_set_payload(const std::string& value);
  std::string* _internal_mutable_payload();
  public:

  // int32 seq = 1;
  void clear_seq();
  ::PROTOBUF_NAMESPACE_ID::int32 seq() const;
  void set_seq(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_seq() const;
  void _internal_set_seq(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 ack = 2;
  void clear_ack();
  ::PROTOBUF_NAMESPACE_ID::int32 ack() const;
  void set_ack(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_ack() const;
  void _internal_set_ack(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int64 timestamp = 4;
  void clear_timestamp();
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_timestamp() const;
  void _internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int32 ack_bits = 3;
  void clear_ack_bits();
  ::PROTOBUF_NAMESPACE_ID::int32 ack_bits() const;
  void set_ack_bits(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_ack_bits() const;
  void _internal_set_ack_bits(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:lab.NetPacket)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr payload_;
  ::PROTOBUF_NAMESPACE_ID::int32 seq_;
  ::PROTOBUF_NAMESPACE_ID::int32 ack_;
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp_;
  ::PROTOBUF_NAMESPACE_ID::int32 ack_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_cpp_5fpbtest_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NetPacket

// int32 seq = 1;
inline void NetPacket::clear_seq() {
  seq_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 NetPacket::_internal_seq() const {
  return seq_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 NetPacket::seq() const {
  // @@protoc_insertion_point(field_get:lab.NetPacket.seq)
  return _internal_seq();
}
inline void NetPacket::_internal_set_seq(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  seq_ = value;
}
inline void NetPacket::set_seq(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_seq(value);
  // @@protoc_insertion_point(field_set:lab.NetPacket.seq)
}

// int32 ack = 2;
inline void NetPacket::clear_ack() {
  ack_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 NetPacket::_internal_ack() const {
  return ack_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 NetPacket::ack() const {
  // @@protoc_insertion_point(field_get:lab.NetPacket.ack)
  return _internal_ack();
}
inline void NetPacket::_internal_set_ack(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  ack_ = value;
}
inline void NetPacket::set_ack(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_ack(value);
  // @@protoc_insertion_point(field_set:lab.NetPacket.ack)
}

// int32 ack_bits = 3;
inline void NetPacket::clear_ack_bits() {
  ack_bits_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 NetPacket::_internal_ack_bits() const {
  return ack_bits_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 NetPacket::ack_bits() const {
  // @@protoc_insertion_point(field_get:lab.NetPacket.ack_bits)
  return _internal_ack_bits();
}
inline void NetPacket::_internal_set_ack_bits(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  ack_bits_ = value;
}
inline void NetPacket::set_ack_bits(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_ack_bits(value);
  // @@protoc_insertion_point(field_set:lab.NetPacket.ack_bits)
}

// int64 timestamp = 4;
inline void NetPacket::clear_timestamp() {
  timestamp_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 NetPacket::_internal_timestamp() const {
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 NetPacket::timestamp() const {
  // @@protoc_insertion_point(field_get:lab.NetPacket.timestamp)
  return _internal_timestamp();
}
inline void NetPacket::_internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  timestamp_ = value;
}
inline void NetPacket::set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:lab.NetPacket.timestamp)
}

// bytes payload = 5;
inline void NetPacket::clear_payload() {
  payload_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& NetPacket::payload() const {
  // @@protoc_insertion_point(field_get:lab.NetPacket.payload)
  return _internal_payload();
}
inline void NetPacket::set_payload(const std::string& value) {
  _internal_set_payload(value);
  // @@protoc_insertion_point(field_set:lab.NetPacket.payload)
}
inline std::string* NetPacket::mutable_payload() {
  // @@protoc_insertion_point(field_mutable:lab.NetPacket.payload)
  return _internal_mutable_payload();
}
inline const std::string& NetPacket::_internal_payload() const {
  return payload_.GetNoArena();
}
inline void NetPacket::_internal_set_payload(const std::string& value) {
  
  payload_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void NetPacket::set_payload(std::string&& value) {
  
  payload_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:lab.NetPacket.payload)
}
inline void NetPacket::set_payload(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  payload_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:lab.NetPacket.payload)
}
inline void NetPacket::set_payload(const void* value, size_t size) {
  
  payload_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:lab.NetPacket.payload)
}
inline std::string* NetPacket::_internal_mutable_payload() {
  
  return payload_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* NetPacket::release_payload() {
  // @@protoc_insertion_point(field_release:lab.NetPacket.payload)
  
  return payload_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void NetPacket::set_allocated_payload(std::string* payload) {
  if (payload != nullptr) {
    
  } else {
    
  }
  payload_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), payload);
  // @@protoc_insertion_point(field_set_allocated:lab.NetPacket.payload)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace lab

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_cpp_5fpbtest_2eproto
